# Generated by Django 6.0.2 on 2026-03-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_products_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='Alok Books',
        ),
    ]
