# Generated by Django 6.0.2 on 2026-03-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_book_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['published_date'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('author', 'book_name')},
        ),
    ]
