# Generated by Django 6.0.2 on 2026-03-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_doctor_engineer_book_alok_books_author__557c21_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['published_date'], 'permissions': [('can_publish', 'Can publish book')], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='positive_price'),
        ),
    ]
