# Generated by Django 6.0.2 on 2026-03-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_book_options_book_positive_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books2',
            fields=[
            ],
            options={
                'proxy': True,
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 5)), name='gte5_price')],
                'indexes': [],
            },
            bases=('home.book',),
        ),
        migrations.RenameIndex(
            model_name='book',
            new_name='AlokBooks_author__7be811_idx',
            old_name='Alok Books_author__557c21_idx',
        ),
        migrations.AddField(
            model_name='skills',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='book',
            table='AlokBooks',
        ),
    ]
