# Generated by Django 6.0.2 on 2026-03-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_books2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books2',
            options={'ordering': ['-price']},
        ),
    ]
