# Generated by Django 6.0.2 on 2026-03-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='images/')),
                ('small_tumbnail', models.ImageField(blank=True, null=True, upload_to='images/thumbnails')),
                ('medium_thumbnail', models.ImageField(blank=True, null=True, upload_to='images/thumbnails')),
                ('large_thumbnail', models.ImageField(blank=True, null=True, upload_to='images/thumbnails')),
            ],
        ),
    ]
